baseurl = "https:/susishushi.github.io/my_blog/"
languageCode = "ja-jp"
publishDir = "docs"
hasCJKLanguage = true
ignoreFiles = ["_files$", "_cache$"]
title = "NSブログ"
theme = "hugo-theme-dream"

# copyright = ""

# googleAnalytics = ""

# disqusShortname = ""

# enableRobotsTXT = true

[params]
  background = "black"
  # backgroundImage = "/me/background.jpg"
  linkColor = "seagreen"

  author = "しゆし"
  # description = ""
  avatar = "/img/avatar.jpg"
  motto = "おれのモットーはとくにない"
  
  email = "@gmail.com"
  # github = ""
  # linkedin = ""
  # codepen = ""
  # stackoverflow = ""

  siteStartYear = 2016

  # favicon = "/favicon.ico"

  # dark mode
  darkLinkColor = "darkseagreen"
  darkNav = true 
  dark404Button = true
