---
title: "[読書感想文]文化がヒトを進化させた"
date: "2020-03-21T00:00:00"
draft: True

categories: ["読書感想文"]
cover: "/img/image_book.png"
tags: ["日記", "読書感想文"]
summary: "「文化がヒトを進化させた―人類の繁栄と〈文化-遺伝子革命〉」を読みました"
---

  <!-- START MoshimoAffiliateEasyLink --><script type="text/javascript">(function(b,c,f,g,a,d,e){b.MoshimoAffiliateObject=a;b[a]=b[a]||function(){arguments.currentScript=c.currentScript||c.scripts[c.scripts.length-2];(b[a].q=b[a].q||[]).push(arguments)};c.getElementById(a)||(d=c.createElement(f),d.src=g,d.id=a,e=c.getElementsByTagName("body")[0],e.appendChild(d))})(window,document,"script","//dn.msmstatic.com/site/cardlink/bundle.js","msmaflink");msmaflink({"n":"文化がヒトを進化させた―人類の繁栄と〈文化-遺伝子革命〉","b":"","t":"","d":"https:\/\/m.media-amazon.com","c_p":"","p":["\/images\/I\/41fFiLZMtyL.jpg"],"u":{"u":"https:\/\/www.amazon.co.jp\/dp\/4826902115","t":"amazon","r_v":""},"aid":{"amazon":"1842760","rakuten":"1824263","yahoo":"1845435"},"eid":"tscCV","s":"s"});</script><div id="msmaflink-tscCV">リンク</div><!-- MoshimoAffiliateEasyLink END -->
  　
  
## 文化ヒトを進化させた―人類の繁栄と〈文化-遺伝子革命〉
  ヒトは、オーストラリアの砂漠から凍てつくシベリアの大地まで、どんな陸生哺乳類よりも多種多様な環境に生息するようになった。それはなぜなのか？
  <br>
  <br>
  本書の冒頭では上記のものを含めた様々な疑問が提起される。我々ヒトの身体は力も弱く、俊敏さにかけ、木登りもできず、消化管も貧弱であり、腸も胃も歯も小さい。そして特大のサイズの脳を持っているにもかかわらず、個々のヒトはそれほど聡明でもない（そんなことはない、という人は是非本書の冒頭でその幻想を打ち砕かれると良い）。
  <br>そんな我々がなぜ地球上のありとあらゆる環境でぶいぶいいわせることができたのだろう？バスケのスター選手が自動車保険を売り込む力を持っているのはなぜ？青い瞳の人がいるのはなぜだろう？信号が青になるまで律義に待つ人が他者と協力して行動する傾向があるのはなぜなのか？
  <br><br>
  それらの答えは、著者によると文化が人の進化を駆動してきたとする「文化－遺伝子共進化」仮説に収斂される（収斂という単語を使ってみたかった）。他者（あるいはその地域集団）を通して学ぶことのできた我々の「文化」こそが、ヒトの解剖学的構造・心理メカニズムを変化させてきたことをこれまでに得られた科学的知見とともに提案する。
  <br>いやもうマジ読んで。こんな記事読んでも伝わらんから。<br>
  <br>
  
## おもしろかったところ  
  
  第12章ヒトの集団脳については特に興味深かった。<br>
個々人が互いに他者から学べるようになるとその社会集団には **集団脳** と呼ぶべき累積的文化進化の産物が生まれる。そのことを例示する頭の良い集団 (テンサイ族) と頭の悪い集団 (チャライ族) による思考実験が以下の通りだ。<br><br>
テンサイ族はチャライ族の100倍賢い。しかし、チャライ族はテンサイ族の10倍社会性に富んでいる。他者から正しく知識を伝えられる可能性が50％だとして、イノベーションが普及するのはどちらか？<br><br>
答えは圧倒的にチャライ族なのだ (本書で紹介されてる参考文献は[こちら]( https://henrich.fas.harvard.edu/files/henrich/files/henrich_2009-2.pdf))。
つまり、クールなテクノロジーを手に入れたければ、頭をよくするよりも人づき合いをよくした方がいい、らしい。学会の懇親会で誰とも懇親できず隅っこでひたすらご飯を食べるマンとなっている私にとっては耳の痛い話だ。チャラくなりたい…。<br>
<br>
<br>
あとこんな話もあった。<br>
読み書き能力の高い人は、言語性情報についての脳領域を特化させることでその隣にある顔認識担当の領域である紡錘状回が割を食うために顔認識が苦手になるらしい。ぼくは昔から顔認識に困難を抱いている（だれがだれだかわからない）のだが、その代償として得られたものがこの記事レベルの読み書き能力だとしたら割に合わない話である。<br>この記事が日本の文化進化を促す集団脳の一助となることを信じて。<br><br><br>

##### 他にこんな本読んだ
[心理学, 認知・行動科学のための反応時間ハンドブック]( https://susishushi.github.io/my_blog/post/rt/)
  <br>
[ヒトの目、驚異の進化](https://susishushi.github.io/my_blog/post/visual_revo/)<br>
[The War for Kindness](https://susishushi.github.io/my_blog/post/buildingemp/)