---
title: "[R]interactions packageのガバガバ紹介"
date: "2019-08-06T00:00:00"
draft: True

categories: ["R"]
cover: "/img/image_PC.png"
tags: ["R"]
summary: "連続変数を含む回帰モデルの交互作用Plot"
---

```{r setup, include=FALSE}
```

連続変数を含む回帰モデルの交互作用を簡単に図示できるパッケージ[(interactions)](https://interactions.jacob-long.com/index.html)の紹介。<br>
このパッケージのいい点  
    1. glm, lmerやbrmsなどの一般化線形、階層、ベイジアンモデルでも適用可能   
    2. 1行で書ける  
    3. 基本連続変数を含むモデルに適用  

## サンプルデータ

使うのはいつものIrisデータ:

```{r iris}
library(interactions)
summary(iris)
```

## interact_plot()

回帰モデルを推定したObjectを用意したら、この関数にぶちこむだけでおわります:

```{r interaction plot}
fit <- lm(Petal.Length ~ Petal.Width*Species, data = iris)
interact_plot(fit, pred = Petal.Width, modx = Species)
```


## 使いそうなやつ簡単に紹介

なんたら区間だの個別データの描画などは以下みたいな感じ:

```{r interaction plot2}
# 変数選択: modx.values
# 個別データplot：plot.points
# 確信・信頼区間：interval (int.width = 0.8で80%区間)
interact_plot(fit, pred = Petal.Width, modx = Species,
              modx.values = c("versicolor", "virginica"), plot.points = T, interval = T)
```

まぁ、基本これだけでいいでしょう。もっと知りたい人は[こちら](https://interactions.jacob-long.com/articles/interactions.html)をどうぞ.

