---
title: "[読書感想文]言葉が呼び求められるとき: 日常言語哲学の復権"
date: "2022-07-12T00:00:00"
draft: True

categories: ["読書感想文"]
cover: "/img/image_book.png"
tags: ["日記", "読書感想文"]
summary: "「言葉が呼び求められるとき: 日常言語哲学の復権」を読みました"
---

<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script language="JavaScript">
$(document).ready( function () {
   $("a[href^='http']:not([href*='" + location.hostname + "'])").attr('target', '_blank');
})
</script>

<!-- START MoshimoAffiliateEasyLink -->
<script type="text/javascript">
(function(b,c,f,g,a,d,e){b.MoshimoAffiliateObject=a;
b[a]=b[a]||function(){arguments.currentScript=c.currentScript
||c.scripts[c.scripts.length-2];(b[a].q=b[a].q||[]).push(arguments)};
c.getElementById(a)||(d=c.createElement(f),d.src=g,
d.id=a,e=c.getElementsByTagName("body")[0],e.appendChild(d))})
(window,document,"script","//dn.msmstatic.com/site/cardlink/bundle.js?20220329","msmaflink");
msmaflink({"n":"言葉が呼び求められるとき: 日常言語哲学の復権","b":"","t":"","d":"https:\/\/m.media-amazon.com","c_p":"\/images\/I","p":["\/51NMr3Z0pFL._SL500_.jpg","\/41BM-FFMl-L._SL500_.jpg","\/51S5QBeonGL._SL500_.jpg","\/31o1F5QrZ7L._SL500_.jpg","\/41JnivE1BmL._SL500_.jpg","\/314L3T47kPL._SL500_.jpg"],"u":{"u":"https:\/\/www.amazon.co.jp\/dp\/4326103043","t":"amazon","r_v":""},"v":"2.1","b_l":[{"id":1,"u_tx":"Amazonで見る","u_bc":"#f79256","u_url":"https:\/\/www.amazon.co.jp\/dp\/4326103043","a_id":1842760,"p_id":170,"pl_id":27060,"pc_id":185,"s_n":"amazon","u_so":1},{"id":2,"u_tx":"楽天市場で見る","u_bc":"#f76956","u_url":"https:\/\/search.rakuten.co.jp\/search\/mall\/%E8%A8%80%E8%91%89%E3%81%8C%E5%91%BC%E3%81%B3%E6%B1%82%E3%82%81%E3%82%89%E3%82%8C%E3%82%8B%E3%81%A8%E3%81%8D%3A%20%E6%97%A5%E5%B8%B8%E8%A8%80%E8%AA%9E%E5%93%B2%E5%AD%A6%E3%81%AE%E5%BE%A9%E6%A8%A9\/","a_id":1824263,"p_id":54,"pl_id":27059,"pc_id":54,"s_n":"rakuten","u_so":2},{"id":3,"u_tx":"Yahoo!ショッピングで見る","u_bc":"#66a7ff","u_url":"https:\/\/shopping.yahoo.co.jp\/search?first=1\u0026p=%E8%A8%80%E8%91%89%E3%81%8C%E5%91%BC%E3%81%B3%E6%B1%82%E3%82%81%E3%82%89%E3%82%8C%E3%82%8B%E3%81%A8%E3%81%8D%3A%20%E6%97%A5%E5%B8%B8%E8%A8%80%E8%AA%9E%E5%93%B2%E5%AD%A6%E3%81%AE%E5%BE%A9%E6%A8%A9","a_id":1845435,"p_id":1225,"pl_id":27061,"pc_id":1925,"s_n":"yahoo","u_so":3}],"eid":"aq4Jd","s":"s"});
</script>
<div id="msmaflink-aq4Jd">リンク</div>
<!-- MoshimoAffiliateEasyLink END -->


「[言葉が呼び求められるとき: 日常言語哲学の復権](https://amzn.to/3axAtN4)」を読んだ。
<br>
<br>
従来の分析哲学における言語観をウィトゲンシュタインとオースティンに依拠して、批判を展開し、日常言語哲学の可能性を再考させる本だった。<br>
<br>
ここでいう従来の分析哲学における言語観（本書では普及版プログラムとしている）というのは、”私たちの言葉と…概念が、それらの適用の来歴のなかでどんな仕事に組されてきたのかという問いを脇に置き、どういうケースに「当てはまるか/適合する」か否かを端的に自問するだけで、それらについて明確な理解を得ることが可能でなければならない、という想定（p. 129-130）”を意味している。<br>
ようは、「知っている」という言葉それ自体が有意味あるいは「真になる」のはどういうときなのか、という意味についての問いである。<br>
この考え方はグライスやサールが支持する分析哲学の根っこにあるものらしい。<br>
<br>
ぐっとくるポイントは「間違いを避ける最善の道は、体系的な言語の理論で武装することだと、これまで示されたことがあったのか。(p 125)」という、我々が持つ (傾向にある) 前提をゆさぶる刺激的な文章である。※著者であるバズは過去の営みが無意味というわけでは決してなく、現象を正しく把握して、取り損ねてそうな現象に無理はさすな、という警句的なものだと僕は理解してる<br>
それをそのまま心理学にもあてはめるのは明らかに筆者の言いたいことを拡張して解釈しているが、このブログはぼくの感想を書くところなので問題ない（多分）。<br>
<br>
ぼくは個人的に感情 (表情) の研究を大学に入ってからずっとしている。その際に、いろんな理論にもであってきた。しかし、そのいずれも満足いく成果にはなっていない。そこで[感情とはそもそも自然種なのか](https://journals.sagepub.com/doi/full/10.1111/j.1745-6916.2006.00003.x?casa_token=CJ6_FjlN8PkAAAAA%3A8OYwaFV-enMCNqUaWtQS4lIWf2a3JxGk7AVXTi6PEEZGCIZ-_kvC4NMXtzUG0jRrJZ7TnUJKrM6rGA)という問いが出たり、[感情に対する不可知論が推奨されたり](https://psycnet.apa.org/record/2017-30838-005)議論はあっちこっちいっている。
その中でぼく個人が見込みがあると現在感じているものは、感情の使用に基づいて解釈しよう、というオースティンの言語行為論に依拠した[Theory of Affective Pragmatics (Scarantino, 2017)](https://people.ict.usc.edu/~gratch/CSCI534/Readings/Scarantino2017.pdf) で、立場としては（名前に反して理論というよりは）日常言語哲学に近いものになるのだろうと勝手に空想している。<br>
そして、従来の感情研究に関する方法論（提示された表情に「幸福」などの感情をラベル付けする）において前提される思考の一種が、本書で扱われる分析哲学と近似する想定を共有しているのかなとも感じた (それすなわち、一つの顔になんらかの感情ラベルを真として対応付ける枠組み：あるいは幸福な感情状態が「真となる」条件を使用を抜きにして語る)。<br>
<br>
そっからまぁいろいろ考えてはいるんですが、そういう意味でも本書4章で詳しく議論される文脈主義（感情研究の文脈では、背景や姿勢、音声などマルチモーダルにすれば真となる感情を見出すことができる、という発想）はそこが依拠する前提の時点で、感情研究においても見込みが薄いものになるのかなぁ、と思ったりもした。もっと詳しい話は、まぁいずれ論文とかにします。するのか？とにかくそういう観点から自分の研究を反省できた点でも、ものすごく価値のある書籍でした。<br>
<br>
ちなみにエピローグのカントのくだりは全然わかんなかった。おそらくぼくが未だに純粋理性批判を読んでいないト―シローであることが問題なのだろう。「日常言語哲学をカントの言葉から見出すのってどういう意義があるの？」という点が気になってしまった。おそらく、哲学領域では過去の著作を独自の観点から読み込んで再解釈する、というのは刺激的な部分なのだろう。<br>
<br>
すでにここまで記事を読んだ人にはわかる通り、事前の知識が結構求められる本なのかもしれない。実際、ぼくがこの本を手にするのは時期尚早だったかもしれない。それでも、ぼくのようななんちゃって語用論勉強マンでも大いに楽しめたので、オースティン、ストローソン、ウィトゲンシュタイン、サール、グライス、らの主な業績を理解したうえで、読めば十分楽しめる内容なんじゃないかとおもう。いやもう知らなくてもいい、本なんてどんな順番で読んでもいいんだ。この本を一番先に読むことで、オースティンら日常言語哲学者の本を見る目線の変化もきっと楽しい体験なんだろう。楽しめ！
<br>
<br>
<br>
  
##### 他にこんな本読んだ
  [グライス　理性の哲学](https://susishushi.github.io/my_blog/post/grice/)
