---
title: "[日記]イギリス留学の備忘録2"
date: "2022-11-15T00:00:00"
draft: True

categories: ["日記"]
cover: "/img/Eng.png"
tags: ["日記"]
summary: "誰かに話そうと思ってたけど誰にも話すことのなかった話題の供養その2"
---
<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script language="JavaScript">
$(document).ready( function () {
   $("a[href^='http']:not([href*='" + location.hostname + "'])").attr('target', '_blank');
})
</script>


イギリスに留学した時期がある。前回の黒歴史は[こちら](https://susishushi.github.io/my_blog/post/england1/)。<br>
<br>
「イギリスで生活する」ということは当然のことながら、「英語を喋る人たちと暮らす」ということだ。<br>
そうなると留学を経験してる人というのは英語がペラペラのように思われるかもしれない。<br>
<br>
しかし、そんなことはない。もちろんそういう人もいるんだろう。少なくとも、自分はそうじゃなかった。<br>
<br>

着いてすぐ留学先のボスには、彼女の同僚(多分ボスより年上の偉い先生)とランチに連れて行ってもらった。優C。<br>
だが連れて行ってもらったはいいものの、ぼくの喋らないこと喋らないこと。口が動かざること山の如しだ。<br>
そもそも英会話以前に、会話が苦手だというのにロンドンについてすぐ英語のフリートークなんてキツすぎる。気を使って同僚の先生が話題を振ってくれた。<br>
<br>
「日本といえばDr. 石黒(ロボット研究で有名な先生)だね。ロボット研究で有名な不気味の谷(ロボットが人の外見に近づくほど不気味さが増す、という現象？)もまた、日本人発祥の概念だけど、日本にはそういう発想の土台があるのかい？(多分こんな質問だったと思う」<br>
<br>
いやむっず。日本語で聞かれたとしてもかなり難易度高いてその質問。当時ロボット工学系の勉強をほぼしてなかったおれの頭におぼろげに浮かんできたのは『ガンダム』だった。あまりにも武器が貧弱。<br>
<br>
同時に思う<br>
「ガンダムの説明を英語でできる気しね～(英語できないやつあるある)<br>
そもそも自分の英語理解が正しいかもわからんから、仮に理解が正しくない場合...<br>
<br>
『ガンダムかなぁ』<br>
『『...(なにが？』』<br>
<br>
こんなことになってしまう。回答としてもギリ意味わからん。てかそもそもおれガンダムを全然知らない。」<br>
<br>
「…I don't know why.(ワカリマセーン」<br>
<br>
ここは勇気の切断ですね。<br>
ちなみに英語のやりとりが拙い上、コミュ障を発揮し、話題を振られたときにこれをするとほぼ確実に「使えないやつ認定」されるので気をつけましょう。せめて、「あなたの質問はこういうことですか？」と聴き直す気概を持ちましょう。ぼくからの遺言です。<br>
<br>
<br>

絶望的な英語力をまざまざと見せつけたぼくであったが、ボスとミーティングをした際「お前の英語力、まじ低すぎるから留学者用の英語コースを別途受けてこい」と言われた。<br>
留学者用の英語コース！さすが一流(ロンドン)大学！そういうサポートもしっかりしてるわけか！<br>
<br>
ちなみにその英語コース担当者に連絡を取ったら何言ってるかわかんなくてその英語コースをそもそも受講できなかった。入門講座に入門すらできないとは青天の霹靂である。(正確には留学したのが10月で今更入るには中途半端なので来るな、的なことを言われた気がする)<br>
<br>

この英語力(のなさ)が役に立つこともあった。ロンドン市内に出たときに「赤ちゃんにミルクが必要でお金が欲しいの」おばさんが現れたことがある。<br>
なんとなくヤバそうな雰囲気が出てたので毅然と「I cannot speak English(英語喋れません」と答えた。<br>
察した相手は「牛乳、、、赤ちゃん、、、お金、、、プリーズ」と単語レベルで教えてくれた。ぼくは理解できないフリを突き通した。<br>
<br>
するとめちゃくちゃ罵声らしい英語を捲し立てられた。もうほんま早口、めっちゃラップ、creepy nutsの生業の大サビみたいなやつ。このフリースタイルダンジョンでは、相手が本当に何を言ってるかわからなかったのでぼくとしてはノーダメージであった。英語できなくてよかった〜(よくない<br>
<br>
こんなぼくでも普通に留学して研究成果を残せたので、みんなも「英語がしゃべれない…」とビビらずにカジュアルに海外に行こう！<br>
<br>


##### 他にこんな記事があるよ
 [イギリス留学の備忘録１](https://susishushi.github.io/my_blog/post/england1/)
  <br>