---
title: "[研究]胎児はお腹の中で母親が食べたものの「味」に表情で反応するのか"
date: 2022-09-27T20:59:19+09:00
draft: true

categories: ["研究"]
cover: "/img/image_pikon.png"
tags: ["研究","日記"]
summary: "妊婦が摂取した食べ物の味に胎児が表情で反応するのか？"
---

<script type="text/javascript" src="//ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
<script language="JavaScript">
$(document).ready( function () {
   $("a[href^='http']:not([href*='" + location.hostname + "'])").attr('target', '_blank');
})
</script>

胎児がお腹の中で食べたものの「味」に反応する、という論文が紹介されて一瞬だけ話題になっていた (参考：[ナゾロジーの記事](https://nazology.net/archives/115204))。<br>
<br>
ここではその論文([こちら](https://journals.sagepub.com/doi/10.1177/09567976221105460))をちゃんと読んでみた結果、そこで得られた解釈が妥当かを考えていく。ただし、表情に関する話題に着目しているので、カプセルの妥当性等はここでは問わないことにする。<br>
<br>
今北産業・忙しい人向けに三行にまとめておく<br>
<br>
・胎児がお腹の中で母親が食べたものの「味」に表情で反応する、という研究が報告された<br>
・表情研究者 (ぼく) がちゃんと読んだ結果、ニンジンが笑顔を引き起こす、という仮説の妥当性が気になった。<br>
・対象となる従属変数の妥当性に関しても少し気になった。<br>
<br>
さて、本題。<br>
<br>
まずこの論文では、妊娠中の母親が接触した食物の化学物質が羊水に溶け込んで、胎児もその味なりにおいなりを認識するだろう。という前提を置いている。<br>
<br>
やってることはシンプル。<br>
妊娠32－36週のお母さんが飲む一回分のカプセル（で伝達されるフレーバー：ニンジン、ケール、何も飲まない統制群の三条件）摂取20分後にscan(25分)を開始<br>
観察可能な顔において統制群と比較して…<br>
ニンジン味 (n = 35) → 口角上昇＋笑顔関連がより多く表出<br>
ケール味 (n = 34) → 上唇上昇＋下唇下降＋唇緊張・圧力＋悲しみ関連がより多く表出<br>
<br>
という結果。<br>
<br>
論文で挙げられた根拠の一つは、「胎児の段階でにおいや味 (カプセルが実際に伝達している感覚はわからないと認めつつ) を弁別する器官はできているはず」というもの。<br>
味覚を受容する器官は14週目にはできて (Witt & Reutter, 1998)、嗅覚を受容する器官は24週目にはできてるらしい (Witt, 2020)、というのが理由として挙げられている。なるほど。<br>
<br>
従来の研究では、妊娠中のお母さんが食べたものによって、生後すぐの新生児がその食べたものに影響を受けた選好を示す、というものが報告されてきた (ニンニク食うママの子供はニンニクを嫌がらない：Hepper, 1995、香草で同じような話：Schaal et al., 2000)。この研究の新規性は生後ではなく、胎児の段階で反応をモニタリングできること。<br>
<br>
その中で重要そうなのは、Mennella et al., (2001)。この研究では、ニンジンジュースを摂取した母親の子供 (生後5-6months) → 普通のシリアルに比べて、ニンジンシリアルに否定的な表情を示さない、という結果を示している。気になるのは、「やっぱニンジンっておいしくないよね？」ってことだ（個人の感想です）。論文内でもニンジンは「Sweet (ふむ)」で「Fruity (わかる)」、「Woody (ん？木質？)」で「Petrol (ガソリン的な？:えぇ…)」なFlavorであることを報告する知見が引用されている (Alasalvar et al., 2001)。<br>
<br>
母親からニンジンを学習した (?) 新生児はそうでない新生児よりもニンジン味をいやがらなかった、という報告をもとに (Mennella et al., 2001)、「ニンジン味のカプセルを母親が飲んだときに、胎児は笑顔を出すだろう」という仮説を筆者は作っている。なんで？<br>
<br>
ここまでで、批判ポイントは「ニンジンってまずくね？」だ。<br>
そして、こっちは直観的・経験的なものだが、「いいにおいをかいだり、おいしいものをたべる時っていうほど笑顔を出すか？」というのがもう一点気になるところだ。<br>
<br>
まずにおい。これは[Delplanque et al. (2009)](https://psycnet.apa.org/doiLanding?doi=10.1037%2Fa0015369) にて、快感情を引き起こすにおい刺激では大頬骨筋 (笑顔に関連する筋肉) の筋電反応が見られない、という結果が得られている。もちろんにおいの種類にもよるが、いいにおいをかいだ時に自分がどういう顔をしそうか思い浮かべてもらえれば、「他人がいない限り、さすがに笑顔まではいかないかなぁ」というのは共有してもらえる感覚ではないだろうか。ましてやニンジンて。<br>
<br>
次に味。ぼくの知る限り、これもやはり「おいしい！」という主観評価と笑顔は想定ほど対応しない気がする。例えば、[de Wijk et al (2014)](https://journals.plos.org/plosone/article?id=10.1371/journal.pone.0093823) では飲み物の好み評定が高いほど真顔になっていた 。[Dibeklioglu et al. (2020)](http://repository.bilkent.edu.tr/bitstream/handle/11693/75434/Automatic_Estimation_of_Taste_Liking_Through_Facial_Expression_Dynamics.pdf?sequence=1) のFig 6(下段がおいしいときの表情) をご確認いただいても、いうほど笑顔は出ていない。個人の経験になるが、ぼくもめちゃくちゃおいしい食べ物を「うまいなぁ」と思いながら食べるとき、めっちゃつらそうな顔をするらしい。いやまぁそれはどうでもいい。<br>
<br>
以上より、「①ニンジンが笑顔を引き起こすプロセスは評価不能で(ゆえにその仮説がなぜできるのかがわからない)、②そもそも味覚・嗅覚的にポジティブな刺激を受けた時に笑顔が出るかはOpen Issue（ましてや胎児）」ということになる。②に関しては、「我々は社会的な抑制・慣習の学習によって表情を抑えることがありうる。胎児のほうが素直なのだ」という指摘もありうるが、それと同等に「表情の筋肉が胎児段階で発達しているか」という問いも残っている。<br>
<br>
<br>
次に方法セクションに行ってみよう。<br>
<br>
まずは手続きの紹介だ。<br>
<br>
原稿4ページ目Procedureより。<br>
一口分の水でカプセルをscan20分前に飲む<br>
→統制群はなんもしないでそのまま25分間scan<br>
→摂取20分後、25分間のscan (24fps) を行う（大体午後3時に）<br>
<br>
<br>
次はコーディングに関して。この原稿を読む前に抱いていた印象は「どうせCodingに恣意性が入ったりしてるんとちゃうん？」だった。そこらへんは匿名化などを工夫して行い、恣意性が入らないようにしているようだ（原稿上は）。<br>
<br>
Codeできるほど顔が見えるscanを対象として選択した（わかる）→胎児ごとに子宮内の位置とかで対象となる時間は異なったけど、条件間で平均時間は似ていたので問題ない（わからない。たまたま顔がよく動く胎児がどこかの条件でいた場合に過剰な表情頻度が生じる＋SEもでかい気がする。より詳細を報告するべき）→一分間ごとの表情表出相対頻度を計算。<br>
<br>
この頻度は以下のように算出するらしい。<br>
The relative frequency of fetal FMs per minute was calculated by dividing the number of the given FMs by the codable time and multiplying the result by 60.<br>
このgiven FMsが「1秒間に一度でも出た表情運動」を指すのか、「Frameレベルの頻度数 (1秒最大24)」を指すのか、は不明瞭なままである。<br>
<br>
計算式もかなりややこしい。胎児Aのscan (25 min) で取り出せた秒数 (表情がCodeできる時間) が480sec (8分) だったとして、特定の表情 (例えば口角の上昇) に関する評価可能性 (codable time) は480だ。口角の上昇回数 (例えば48回) を480で割って、60で掛ければ、一分間で生じることが期待される表情運動の生起頻度がわかる、はず（48/480 = 0.1 → 0.1 * 60 = 6: 一分間で大体6回口角上昇が観察される?）。<br>
しかし、本当にそんな数が平均として得られているのだろうか？「1秒間の表情運動」ってざっくりすぎないか？そんな疑問に答えるのが、相対頻度の次に紹介される指標だ。<br>
<br>
the total codable footage of each scan was coded frame by frame to identify discrete FMs displayed by the fetus.<br>
<br>
なるほど。これは明らかにフレームごとに、新生児によって表出された表情運動の総数を教えてくれるのだろう。しかし、驚いたことにこの指標は特に何の説明もなく闇へと葬られる。続くStatistical analysisセクションで記述される、All dependent variablesの中に、この total codable footage と思しき指標は見つからない。実際結果セクションでは、がっつり相対頻度が解析結果にも図にも表示されるが、この指標に関する図は見つけられない。<br>
（もしぼくが見過ごしてるのであればご指摘いただければ助かります）<br>
<br>
<br>
例えば、ケール条件の”相対頻度”に関する最も高い平均値はざっくり0.35だ (Fig 3参照)。平均Codable timeを480として逆算してみよう。0.35を60で割る (0.0058)。その後に、Codable time 480を掛けてみる。すると2.78秒となる。そしてこの約66Frame (2.78 * 24 fps) の中に特定の表情がどの程度含まれているかはわからないままだ。95%CIで適当に考えると2－3秒ほど見られた表情運動がある、ということになる。0.35という値が意味するのは「60秒間のうち、大体約3秒くらいは当該表情運動がみれるかな (Frameレベルだと知らん)」だ。<br>
（この指標、もし理解が間違ってたらご指摘いただければ助かります）<br>
<br>
しかし、査読者はこの指標を正しく理解できていたのだろうか？（そしてぼくは正しく理解できているのだろうか？）<br>
あなたが心理学研究者かつこの論文の査読者だとして、この指標を「まぁ筆者が言うんだからそうなんだろう」と思わずに「なにかおかしいぞ？」とつっこめるだろうか。まさか、「Relative Frequencyが0.35ということは、大体35％がこの特定表情運動を表出したのだな」と思うことはあるまい (表情研究者であれば、この条件でこの値は高すぎる、とすぐにわかる)。しかし、このRelative Frequencyという単語はそういうミスリーディングを起こしうる、という意味で少し危ういと個人的には思う。<br>
<br>
Rawデータがないとどういう特徴を具体的に持つデータなのかは、この原稿からではどうしてもわからない。雰囲気しかわからないのだ。なんか表情に関する計算をCodingできるとこだけ抽出して、図を見れば確かになんかケールカプセル摂取したときのほうが表情が出ている、というレベルの解像度でしか結果を理解できない。<br>
<br>
現象をそのまま記述して（意味わからん指標作って対数変換したりとかせずに）、ベルヌーイ分布とかポアソン分布みたいなモデルをあてはめたほうが良いような気もする。ただ、それによって結論が変化するかはぼくにはわからない。はっきりしたことはわからないのだ。この指標の解釈も個人的には「表情の表出に関するなにかではあるけど、すげーよくわからんもの」という印象にならざるを得ない。<br>
<br>
ちなみにこの論文で扱うGestaltは理解に苦しむ指標なので、ここでは触れない。共起関係を意味のない枠組みで説明してるだけだ（個人の感想です）。<br>
<br>
最終的なコーディング数 (data point) はどうなって、どれだけの情報が集約されたのか。
Frameレベルでの頻度数でなく、相対指標だけを扱うのだとしたら、結果の解像度が低すぎないか？<br>
<br>
また、様々な写り方や角度のしわでそういう計算になる可能性もあるが (e.g., [Witkower and Tracy, 2019](https://journals.sagepub.com/doi/abs/10.1177/0956797619838762))、そこは筆者を信じるとしよう。<br>
<br>
以上より、もっとも重要な従属変数がめちゃくちゃわかりずらいうえに、実際にどの程度その表情が見られたのか、という指標の記述が甘すぎる。そのうえデータも公開されてないので、個人の見解としては、この研究結果を信頼しきることはできないと思う。<br>
<br>
さてあとはそれっぽい考察と生後の影響とかも加味して調べられたらいいよね、的なことが書いてあるだけなのでカットする。<br>
<br>
<br>
まとめると、①笑顔に関する仮説が気になった。②従属変数が気になった。なので、図で見た平均値の違いはインパクトがあるけど、その差が具体的にどういうものかはやっぱりよくわからないまま。といったところだろうか。そもそもまずいものを食う時ならわかるが、おいしいものを食べるとき、素朴に想定されているほど我々は笑顔を作らないはず、というのが個人の経験としてある (日常でも研究レベルでも)。それにもかかわらず、驚くほどこの研究では口角上昇がほかの条件と比べて表出されている (図の上では)。ここがやはり個人的には気になるところだ。手続きは充分追試できそうなものなので、自分でもぜひやってみたい（技術がある人、お声かけお待ちしております）。<br>
<br>
結論としては、この研究で得られた結果の解釈は個人としては妥当と言い切れるものでない印象を持った。しかしそれはこの研究が「無意味だ」というつもりでは、全くない。とはいえ誤解を招きそうな表現がいくつか入っているこの知見が、インパクトを持って (Psychological Scienceは心理学領域ではインパクトが高めの雑誌なのだ) 一般社会に喧伝されることに関しては、一研究者として懸念を抱かずにはいられないな、と思った。<br>
<br>
最後に、このニュースをみて、子宮内の胎児と母親の食事に関する関係で不安になった方もいるかと思います。[2019年のレビュー](https://pubmed.ncbi.nlm.nih.gov/30982867/)によると、妊娠・授乳中の母親の食事と子供の食事との関係についての科学的な結論は出せない、ということです。妊娠・授乳中の皆様におかれましては、食事に対して過度に神経質になりすぎず、リラックスして毎日をお過ごしください。
<br>
<br>
あー疲れた。もうこういうことしないかも。<br>

