---
title: "[読書感想文]心理学, 認知・行動科学のための反応時間ハンドブック"
date: "2020-03-12T00:00:00"
draft: True

categories: ["読書感想文"]
cover: "/img/image_book.png"
tags: ["日記", "読書感想文"]
summary: "「心理学, 認知・行動科学のための反応時間ハンドブック」を読みました"
---

  
  <!-- START MoshimoAffiliateEasyLink --><script type="text/javascript">(function(b,c,f,g,a,d,e){b.MoshimoAffiliateObject=a;b[a]=b[a]||function(){arguments.currentScript=c.currentScript||c.scripts[c.scripts.length-2];(b[a].q=b[a].q||[]).push(arguments)};c.getElementById(a)||(d=c.createElement(f),d.src=g,d.id=a,e=c.getElementsByTagName("body")[0],e.appendChild(d))})(window,document,"script","//dn.msmstatic.com/site/cardlink/bundle.js","msmaflink");msmaflink({"n":"心理学、認知・行動科学のための反応時間ハンドブック","b":"勁草書房","t":"","d":"https:\/\/m.media-amazon.com","c_p":"","p":["\/images\/I\/51NhuL-epJL.jpg"],"u":{"u":"https:\/\/www.amazon.co.jp\/dp\/4326251360","t":"amazon","r_v":""},"aid":{"amazon":"1842760","rakuten":"1824263","yahoo":"1845435"},"eid":"qKTiL","s":"s"});</script><div id="msmaflink-qKTiL">リンク</div><!-- MoshimoAffiliateEasyLink END -->
  　
  　
  
## 心理学, 認知・行動科学のための反応時間ハンドブック 
  反応時間研究に関わるすべての研究者・学生必読！と宣伝されてる「心理学, 認知・行動科学のための反応時間ハンドブック」を読みました。
  
  刺激の入力（知覚）⇒処理⇒反応生成、というプロセスを反応時間という指標を通して具に観察していく先駆者のお話が記載されていて最高ですね。
  <br>
  <br>
  
## どういう人におすすめか  
  
  この本は実験心理学について学ぶ上での最初の一歩として最適な書籍のような気がします。反応時間に関する説明をするうえで「実験とはなにか」、「実験課題を設計しておく上で、留意するべきことはなにか」などの心理学実験を行う上で基礎的かつ重要なポイントがまとめられてるのがすばらしんごです。
  
  そしてもちろん、古典的実験についての近年の動向も追うことができる点で研究者にとっても垂涎ものの一品です。
  <br>
  <br>
  
## 興奮したところ  
  反応時間計測の発端は天文学者による天体観測って話とか、反応時間に対する色んな分析手法とか全然知らなかったのでそういう普段は自分から調べたりしない反応時間に関するいろんなトピックを体系的に学ぶことができたのがとってもよかったです（小学生並みの感想
  
  個人的にはウェブ実験についての章が興味深かったです。最近はウェブ実験で反応時間を測定する課題をやってみようかな～と思っているのでここで紹介されているフィッティングアプローチからWeb実験と実験室実験の反応時間の分布が全体的な位置を除けばある程度一致していたのはかなり励みになったし、自分でも原典にちゃんと目を通してみようとなった。（ちなみに元論文は[こちら](https://www.ncbi.nlm.nih.gov/pubmed/26170056)）
  
  さらにもう少しマニアックなもので試行数と検出力の関連についての研究を紹介しているコラムにもとっても興奮しました。実験心理学者のこれまでの営みを、こんなに濃厚かつ凝縮に紹介しているなんて最高やぞ！
  
  

  みんなもチェックするんじゃぞ！
<br>
<br>
##### 他にこんな本読んだ  
  [心理学, 認知・行動科学のための反応時間ハンドブック](https://susishushi.github.io/my_blog/post/cul_evo/)
  <br>